#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -n ${HISHTORY_POSTGRES_DB} ]]; then
    DBHOST=$(echo "${HISHTORY_POSTGRES_DB}" | awk -F '@' '{print $NF}' | awk -F ':' '{print $1}')
    DBPORT=$(echo "${HISHTORY_POSTGRES_DB}" | awk -F '@' '{print $NF}' | awk -F ':' '{print $2}' | awk -F '/' '{print $1}')
else
    echo "No database configured, sleeping..."
    sleep infinity
fi

echo "Waiting for DB ${DBHOST} to become available on port ${DBPORT}..."
while :; do
    if nc -w 1 -z "$DBHOST" "$DBPORT" > /dev/null 2>&1; then
        exit 0
    fi
    sleep 3
done
