#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            s6-setuidgid abc /app/server
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            /app/server
fi
